dist:         xenial
language:     python
python:
  - 3.7
services:
  - docker

git:
  depth:      1

branches:
  only:
    - master
jobs:
  include:
    - stage:  deploy
      script:
        - gcloud components update
        - cat ${GCP_ACCOUNT_CREDENTIALS} > creds.json
        - gcloud auth activate_service_account --keyfile=creds.json
        - cd patchserver && ./cf-deploy.sh
