dist:       xenial
language:   python
python:
- 3.7
services:
- docker
git:
  depth:    1
branches:
  only:
  - master
jobs:
  include:
  - stage:  deploy
    script:
    - openssl aes-256-cbc -K $encrypted_43783f5f9db0_key -iv $encrypted_43783f5f9db0_iv
      -in creds.json.enc -out creds.json -d
    - gcloud components update
    - gcloud auth activate_service_account --keyfile=creds.json
    - cd patchserver && ./cf-deploy.sh
