dist:          xenial
language:      python
python:
- 3.7
services:
- docker
git:
  depth:       1
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
branches:
  only:
  - master
jobs:
  include:
  - stage:     deploy
    script:
    - openssl aes-256-cbc -K $encrypted_43783f5f9db0_key -iv $encrypted_43783f5f9db0_iv
      -in creds.json.enc -out creds.json -d
    - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk;
      export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com |
      bash; fi
    - export PATH="${HOME}/google-cloud-sdk/bin":$PATH
    - which gcloud
    - gcloud components update
    - gcloud auth activate-service-account --key-file=creds.json
    - cd patchserver && ./cf-deploy.sh
  - stage:     deploy
    script:
    - openssl aes-256-cbc -K $encrypted_43783f5f9db0_key -iv $encrypted_43783f5f9db0_iv
        -in creds.json.enc -out creds.json -d
    - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk;
        export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com |
        bash; fi
    - export PATH="${HOME}/google-cloud-sdk/bin":$PATH
    - which gcloud
    - gcloud components update
    - gcloud auth activate-service-account --key-file=creds.json
    - if [ -z $(git diff --name-only HEAD HEAD~1 caterator) ]; then cd caterator && ./deploy_frontend.sh; fi
